name: Deploy React App to Pages

on:
  push:
    branches: ["main"]

# Permisos necesarios para interactuar con GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar proyecto de React
        run: npm run build

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir artefactos de compilación
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
